query team ($id: ID!) {
  team(id: $id) {
      id
      name
      socialProfiles {
          edges{
            node{
                id
                name
                socialNetwork
                profilePicture
                facebookPageName
            }
          }
      }
  }
}
