query ($calendarSlotIds: [ID], $categoryIds: [ID], $profileIds: [ID]) {
  contentSchedules_find(calendarSlotIds: $calendarSlotIds, categoryIds: $categoryIds, profileIds: $profileIds) {
    edges {
      node {
        id
        type
        socialProfile {
          id
          name
        }
        publishAt
        moderationStatus
        content {
          id
          text
          inBank
          evergreen
          published
          media {
            id
            url
          }
        }
        calendarSlot {
          id
          day
          time
          type
        }
      }
    }
  }
}
